openapi: '3.0.2'

info:
  title: Medium API
  version: '1.0'
  x-twitter: 'https://twitter.com/medium_api'
  x-linkedin: 'https://www.linkedin.com/company/medium-api'
  x-logo:
    url: https://mediumapi.com/imgs/logo/logo-primary-color.svg
  description: >
    Medium API helps you to quickly extract data from Medium's Website (https://medium.com). 
    
    
    You can gather data related to users, publications, articles (including its textual content), latest posts & top writers within a topic/niche, etc…
  contact:
    name: Nishu Jain
    email: nishu@mediumapi.com
    url: https://mediumapi.com

  termsOfService: https://github.com/weeping-angel/medium-apis/raw/pages/terms_of_use.pdf

tags: 
  - name: Welcome
  - name: User
  - name: Publication
  - name: Article
  - name: Misc
  - name: List
  - name: Search

externalDocs:
  description: Read more on Medium
  url: 'https://medium.com/geekculture/medium-api-documentation-90a01549d8db'

servers:
  - url: https://medium2.p.rapidapi.com

paths:
  /:
    $ref: './paths/welcome.yml'

  # User Endpoints

  /user/id_for/{username}:
    $ref: './paths/user_id_for.yml'
  /user/{user_id}:
    $ref: './paths/user_info.yml'
  /user/{user_id}/following:
    $ref: './paths/user_following.yml'
  /user/{user_id}/followers:
    $ref: './paths/user_followers.yml'
  /user/{user_id}/articles:
    $ref: './paths/user_articles.yml'
  /user/{user_id}/top_articles:
    $ref: './paths/user_top_articles.yml'
  /user/{user_id}/interests:
    $ref: './paths/user_interests.yml'
  /user/{user_id}/lists:
    $ref: './paths/user_lists.yml'
  /user/{user_id}/publications:
    $ref: './paths/user_publications.yml'

  # Article Endpoints
  
  /article/{article_id}:
    $ref: './paths/article_info.yml'
  /article/{article_id}/content:
    $ref: './paths/article_content.yml'
  /article/{article_id}/markdown:
    $ref: './paths/article_markdown.yml'
  /article/{article_id}/responses:
    $ref: './paths/article_responses.yml'
  /article/{article_id}/fans:
    $ref: './paths/article_fans.yml'
  /article/{article_id}/related:
    $ref: './paths/related_articles.yml'
  
  # Publication Endpoints
  
  /publication/id_for/{publication_slug}:
    $ref: './paths/publication_id_for.yml'
  /publication/{publication_id}:
    $ref: './paths/publication_info.yml'
  /publication/{publication_id}/articles:
    $ref: './paths/publication_articles.yml'
  /publication/{publication_id}/newsletter:
    $ref: './paths/publication_newsletter.yml'
  
  # Misc Endpoints
  
  /topfeeds/{tag}/{mode}:
    $ref: './paths/topfeeds.yml'
  /top_writer/{topic_slug}:
    $ref: './paths/top_writers.yml'
  /latestposts/{topic_slug}:
    $ref: './paths/latestposts.yml'
  /related_tags/{tag}:
    $ref: './paths/related_tags.yml'

  # List Endpoints

  /list/{list_id}:
    $ref: './paths/list_info.yml'
  /list/{list_id}/articles:
    $ref: './paths/list_articles.yml'
  /list/{list_id}/responses:
    $ref: './paths/list_responses.yml'

  # Search Endpoints

  /search/users?query={query}:
    $ref: './paths/search_users.yml'
  /search/publications?query={query}:
    $ref: './paths/search_publications.yml'
  /search/articles?query={query}:
    $ref: './paths/search_articles.yml'
  /search/tags?query={query}:
    $ref: './paths/search_tags.yml'
  /search/lists?query={query}:
    $ref: './paths/search_lists.yml'

  
components:
  securitySchemes:
    ApiKey: 
      type: apiKey
      in: header
      name: x-rapidapi-key
    ApiHost:
      type: apiKey
      in: header
      name: x-rapidapi-host
  
  

